### ISSUE TITLE
atom styles

### ISSUE THREAD

**Issue by mmagnuski** [mmagnuski/my-settings#2]
Add this to atom `styles.less`:

``` less
// style background for one-dark-ui theme only
.theme-one-dark-ui atom-text-editor {
  background-color: hsl(222, 11%, 11%);
}
```
